name: fagotinni
description: Daily practice companion for woodwind musicians.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  audioplayers: ^6.5.1
  record: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
